CREATE TABLE IF NOT EXISTS "holidays" (
  "id" SERIAL PRIMARY KEY,
  "date" TIMESTAMP(3) NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "source" TEXT NOT NULL DEFAULT 'custom',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
